---
#-
#  _                _                            _
# | | _____   _____| | __ _  ___ ___       _   _(_)
# | |/ _ \ \ / / _ \ |/ _` |/ __/ _ \_____| | | | |
# | | (_) \ V /  __/ | (_| | (_|  __/_____| |_| | |
# |_|\___/ \_/ \___|_|\__,_|\___\___|      \__,_|_|
#
#

background: var(--background-image)
decluttering_templates:
  automation_template:
    card:
      card:
        show_header_toggle: false
        title: '[[name]] automations'
        type: entities
      filter:
        include:
          - entity_id: automation.[[slug]]*
      sort: entity_id
      type: custom:auto-entities
title: Home Control Panel

views:
  - !include lovelace/main.yaml
  - !include lovelace/system_info.yaml
