---
#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
- platform: group
  name: all_phones
  services:
    - service: mobile_app_joaos_iphone
    - service: mobile_app_redmi_note_8_pro

- platform: group
  name: joao
  services:
    - service: mobile_app_joaos_iphone

- platform: group
  name: sandra
  services:
    - service: mobile_app_redmi_note_8_pro
